"use client"

import { useState, useEffect } from "react"
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetDescription } from "@/components/ui/sheet"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Badge } from "@/components/ui/badge"
import { DecorIcon } from "@/components/decor-icon"
import { FullWidthDivider } from "@/components/full-width-divider"
import { Mail, Send, Clock, Bot, CheckCircle2, AlertCircle, RefreshCw } from "lucide-react"
import { toast } from "sonner"

interface FollowUpData {
  applicationId: string
  companyName: string
  jobTitle: string
  status: string
  businessDaysElapsed: number
  isFollowUpDue: boolean
  followUpStatus: string
  draft: {
    subject: string
    body: string
    checklist?: string[]
    generatedAt?: string
  } | null
}

interface FollowUpSendDrawerProps {
  applicationId: string | null
  open: boolean
  onOpenChange: (open: boolean) => void
  onFollowUpSent?: () => void
}

export function FollowUpSendDrawer({
  applicationId,
  open,
  onOpenChange,
  onFollowUpSent,
}: FollowUpSendDrawerProps) {
  const [data, setData] = useState<FollowUpData | null>(null)
  const [loading, setLoading] = useState(false)
  const [generating, setGenerating] = useState(false)
  const [sending, setSending] = useState(false)
  const [toEmail, setToEmail] = useState("")
  const [subject, setSubject] = useState("")
  const [body, setBody] = useState("")

  useEffect(() => {
    if (!open || !applicationId) {
      setData(null)
      return
    }

    let isMounted = true
    setLoading(true)

    fetch(`/api/applications/${applicationId}/follow-up`)
      .then((res) => {
        if (!res.ok) throw new Error("Failed to load follow-up details")
        return res.json()
      })
      .then((resData: FollowUpData) => {
        if (!isMounted) return
        setData(resData)
        if (resData.draft) {
          setSubject(resData.draft.subject || "")
          setBody(resData.draft.body || "")
        } else {
          setSubject("")
          setBody("")
        }
      })
      .catch((err) => {
        if (!isMounted) return
        toast.error(err instanceof Error ? err.message : "Error loading follow-up")
      })
      .finally(() => {
        if (isMounted) setLoading(false)
      })

    return () => {
      isMounted = false
    }
  }, [open, applicationId])

  const handleGenerate = async () => {
    if (!applicationId) return
    setGenerating(true)
    try {
      const res = await fetch(`/api/applications/${applicationId}/follow-up`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ action: "generate" }),
      })
      const result = await res.json()
      if (!res.ok) throw new Error(result.error || "Failed to generate draft")

      setData((prev) =>
        prev
          ? {
              ...prev,
              draft: result.draft,
              followUpStatus: "DRAFTED",
            }
          : null
      )
      setSubject(result.draft?.subject || "")
      setBody(result.draft?.body || "")
      toast.success("Follow-up draft generated by Career Copilot")
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "Generation failed")
    } finally {
      setGenerating(false)
    }
  }

  const handleSend = async () => {
    if (!applicationId) return
    if (!subject.trim() || !body.trim()) {
      toast.error("Subject and body cannot be empty")
      return
    }

    setSending(true)
    try {
      const res = await fetch(`/api/applications/${applicationId}/follow-up`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          action: "send",
          toEmail: toEmail.trim() || undefined,
          customSubject: subject,
          customBody: body,
        }),
      })
      const result = await res.json()
      if (!res.ok) throw new Error(result.error || "Failed to dispatch follow-up")

      toast.success("Follow-up email dispatched via Gmail successfully!")
      onFollowUpSent?.()
      onOpenChange(false)
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "Dispatch failed")
    } finally {
      setSending(false)
    }
  }

  return (
    <Sheet open={open} onOpenChange={onOpenChange}>
      <SheetContent
        side="right"
        className="w-full sm:max-w-xl p-0 flex flex-col bg-background border-l border-border"
      >
        <SheetHeader className="p-6 pb-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <div className="p-1.5 rounded bg-primary/10 border border-primary/20 text-primary">
                <Mail className="h-4 w-4" />
              </div>
              <SheetTitle className="text-base font-semibold tracking-tight">
                5-Day Follow-Up Studio
              </SheetTitle>
            </div>
            <DecorIcon className="text-muted-foreground/40" />
          </div>
          <SheetDescription className="text-xs text-muted-foreground mt-1">
            Automated outreach to re-engage recruiters after dormancy.
          </SheetDescription>
        </SheetHeader>

        <FullWidthDivider />

        <div className="flex-1 overflow-y-auto p-6 space-y-6">
          {loading ? (
            <div className="flex flex-col items-center justify-center h-48 space-y-3">
              <RefreshCw className="h-6 w-6 animate-spin text-muted-foreground" />
              <p className="text-xs text-muted-foreground">Loading follow-up context...</p>
            </div>
          ) : !data ? (
            <div className="flex flex-col items-center justify-center h-48 space-y-2 text-center">
              <AlertCircle className="h-8 w-8 text-muted-foreground" />
              <p className="text-sm font-medium">Application details not found</p>
            </div>
          ) : (
            <>
              {/* Context bar */}
              <div className="flex items-center justify-between p-3.5 rounded-lg border border-border bg-card/40">
                <div>
                  <h4 className="text-sm font-semibold">{data.companyName}</h4>
                  <p className="text-xs text-muted-foreground">{data.jobTitle}</p>
                </div>
                <div className="flex items-center gap-2">
                  <Badge variant={data.isFollowUpDue ? "destructive" : "secondary"} className="text-xs">
                    <Clock className="h-3 w-3 mr-1 inline" />
                    {data.businessDaysElapsed} business days
                  </Badge>
                  {data.isFollowUpDue && (
                    <Badge variant="outline" className="text-xs border-amber-500/30 text-amber-500 bg-amber-500/10">
                      Follow-up Due
                    </Badge>
                  )}
                </div>
              </div>

              {/* Action Banner */}
              {!data.draft ? (
                <div className="p-4 rounded-lg border border-border/80 bg-muted/20 space-y-3">
                  <div className="flex items-start gap-3">
                    <Bot className="h-5 w-5 text-primary shrink-0 mt-0.5" />
                    <div className="space-y-1">
                      <h5 className="text-xs font-semibold">No Follow-Up Draft Staged</h5>
                      <p className="text-xs text-muted-foreground">
                        Career Copilot can synthesize your background and application timing to draft a polite, high-converting re-engagement email.
                      </p>
                    </div>
                  </div>
                  <Button
                    onClick={handleGenerate}
                    disabled={generating}
                    className="w-full text-xs font-medium"
                  >
                    {generating ? (
                      <>
                        <RefreshCw className="h-3.5 w-3.5 mr-2 animate-spin" />
                        Generating Draft...
                      </>
                    ) : (
                      <>
                        <Bot className="h-3.5 w-3.5 mr-2" />
                        Generate Strategic Draft
                      </>
                    )}
                  </Button>
                </div>
              ) : (
                <div className="space-y-4">
                  <div className="space-y-1.5">
                    <label className="text-xs font-semibold text-muted-foreground uppercase tracking-wider">
                      Recipient Email (Optional if replying to thread)
                    </label>
                    <Input
                      type="email"
                      placeholder="recruiter@company.com"
                      value={toEmail}
                      onChange={(e) => setToEmail(e.target.value)}
                      className="text-xs"
                    />
                  </div>

                  <div className="space-y-1.5">
                    <label className="text-xs font-semibold text-muted-foreground uppercase tracking-wider">
                      Subject Line
                    </label>
                    <Input
                      value={subject}
                      onChange={(e) => setSubject(e.target.value)}
                      className="text-xs font-medium"
                    />
                  </div>

                  <div className="space-y-1.5">
                    <label className="text-xs font-semibold text-muted-foreground uppercase tracking-wider">
                      Message Body
                    </label>
                    <Textarea
                      rows={9}
                      value={body}
                      onChange={(e) => setBody(e.target.value)}
                      className="text-xs leading-relaxed font-mono"
                    />
                  </div>

                  {data.draft.checklist && data.draft.checklist.length > 0 && (
                    <div className="p-3 rounded-lg border border-border bg-card/30 space-y-2">
                      <div className="text-xs font-semibold flex items-center gap-1.5">
                        <CheckCircle2 className="h-3.5 w-3.5 text-emerald-500" />
                        Strategic Validation Checklist
                      </div>
                      <ul className="space-y-1 text-xs text-muted-foreground">
                        {data.draft.checklist.map((item, idx) => (
                          <li key={idx} className="flex items-start gap-1.5">
                            <span className="text-muted-foreground/60">•</span>
                            <span>{item}</span>
                          </li>
                        ))}
                      </ul>
                    </div>
                  )}
                </div>
              )}
            </>
          )}
        </div>

        <FullWidthDivider />

        <div className="p-4 bg-muted/10 flex items-center justify-between gap-3">
          <Button
            variant="ghost"
            size="sm"
            onClick={() => onOpenChange(false)}
            className="text-xs"
          >
            Cancel
          </Button>

          {data?.draft && (
            <div className="flex items-center gap-2">
              <Button
                variant="outline"
                size="sm"
                onClick={handleGenerate}
                disabled={generating || sending}
                className="text-xs"
              >
                {generating ? (
                  <RefreshCw className="h-3.5 w-3.5 animate-spin" />
                ) : (
                  <>
                    <RefreshCw className="h-3.5 w-3.5 mr-1.5" />
                    Regenerate
                  </>
                )}
              </Button>
              <Button
                size="sm"
                onClick={handleSend}
                disabled={sending || generating}
                className="text-xs font-medium"
              >
                {sending ? (
                  <>
                    <RefreshCw className="h-3.5 w-3.5 mr-1.5 animate-spin" />
                    Sending...
                  </>
                ) : (
                  <>
                    <Send className="h-3.5 w-3.5 mr-1.5" />
                    Send Follow-Up Now
                  </>
                )}
              </Button>
            </div>
          )}
        </div>
      </SheetContent>
    </Sheet>
  )
}
